common:
  vpn_cidr: "10.203.0.0/16"
  vpc_cidr: "192.168.0.0/16"

workspaces:
  aws-infra-us-east-1-qa:
    aws:   
      region: "us-east-1"
      account_id: 
    account_name: aws-infra
    environment_name: "qa"
    project_name : "ecs-infra"

    ecs_service:
      name: "nginx"
      autoscaling:
        cpu:
          scale_in_cooldown: 60
          scale_out_cooldown: 60
          target_value: 90
        memory:
          scale_in_cooldown: 60
          scale_out_cooldown: 60
          target_value: 90

    container_definitions:
      container_name: "nginx"
      # cluster_arn: "arn:aws:ecs:us-east-1:331851393000:cluster/ecs-ec2"
      # target_group_arn: "arn:aws:elasticloadbalancing:us-east-1:331851393000:targetgroup/demo-ngnix/7ff049096103eeb3"
      image: "nginx:latest"
      name: "nginx"
      containerPort: 80
      protocol: "tcp"

    load_balancer:
#      container_name: "demo-1"
      container_port: 80
      subnet_ids: ["subnet-01dcaf8e531b9fd7e", "subnet-075d159e662923fd8"]
